# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(default='', max_length=20, verbose_name='车牌')),
                ('srcaddr', models.CharField(default='', max_length=20, verbose_name='出发地点')),
                ('dstaddr', models.CharField(default='', max_length=20, verbose_name='到达地点')),
            ],
            options={
                'verbose_name': '租方汽车信息',
                'verbose_name_plural': '租方汽车信息',
            },
        ),
    ]
