# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-10 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eastcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalcarinfo',
            options={'ordering': ('carid',), 'verbose_name': '租方汽车信息', 'verbose_name_plural': '租方汽车信息'},
        ),
    ]
